### ISSUE TITLE
Issue when it passes query parameters

### ISSUE THREAD

**Issue by will89pinilla** [amancevice/python-lambda-gateway#10]
Hi everyone,

making some tests, I identified that the library is generating an error when it passes path parameters from URL, for example: 

(venv) willp@willp-vm:~/ms-dc-proj/copies/s3TrafficLight/src/app$ lambda-gateway -p 8443 -t 3 app.handler
Serving HTTP on 0.0.0.0 port 8443 (http://0.0.0.0:8443/) ...
::1 - - [6/Apr/2022 11:16:09] INFO - Invoking "app.handler"

Event print:
{'version': '2.0', 'body': '', 'routeKey': 'DELETE /authorization/1', 'rawPath': '/authorization/1', 'rawQueryString': '', 'headers': {'User-Agent': 'PostmanRuntime/7.28.4', 'Accept': '*/*', 'Postman-Token': '52df702e-63d7-45c1-80f7-5d51759025a1', 'Host': 'localhost:8443', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive'}, 'queryStringParameters': {}, 'requestContext': {'http': {'method': 'DELETE', 'path': '/authorization/1'}}}

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 33150)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/home/willp/ms-dc-proj/copies/s3TrafficLight/venv/lib/python3.8/site-packages/lambda_gateway/request_handler.py", line 7, in do_DELETE
    self.invoke('DELETE')
  File "/home/willp/ms-dc-proj/copies/venv/lib/python3.8/site-packages/lambda_gateway/request_handler.py", line 110, in invoke
    status = res.get('statusCode') or 500
AttributeError: 'NoneType' object has no attribute 'get'

I really appreciate the help if is there any why to handle this, thanks

**Comment by amancevice** [comment]
Let me see if I understand:

You have an API Gateway route — something like `DELETE /authorization/{authId}` — and you want the event generated from `curl -X DELETE http://localhost:8443/authorization/1` to be assigned the `routeKey` with the parameter `{authId}`, and not the literal `DELETE /authorization/1`

is that right?

**Comment by will89pinilla** [comment]
> Let me see if I understand:
> 
> You have an API Gateway route — something like `DELETE /authorization/{authId}` — and you want the event generated from `curl -X DELETE http://localhost:8443/authorization/1` to be assigned the `routeKey` with the parameter `{authId}`, and not the literal `DELETE /authorization/1`
> 
> is that right?

Hi amancevice,

Well I tried to send from CURL a new request using a path param and the lambda-gateway is not working when you send path params, in my case I tried only with this http://localhost:8443/authorization/1 the one was the param and it threw that exception.
